version: '3.8'

services:
  backend:
    build: ./app/backend
    container_name: PodborBotBackend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend/data:/app/data
      - ./app/backend:/app
    environment:
      - DB_PATH=/app/data/database.db
    restart: always

  bot:
    build: ./app/bot
    container_name: PodborBotWorker
    volumes:
      - ./app/bot:/app
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always